(princ "Test file to check the run of apply_items,, compose_items and unify")
(terpri)
(terpri)

(princ "=======================")
(terpri)
(princ "Test 1: apply_items")
(terpri)
(princ "=======================")
(terpri)
(terpri)
(apply_items_test '((A (? x)) (y (? z)) ((f h) (? k)) ) '((? x) (g (f (? k))) (f2 (? z)) ))

(princ "=======================")
(terpri)
(princ "Test 2: compose_items")
(terpri)
(princ "=======================")
(terpri)
(terpri)
(compose_items_test  '((G ((? X) (? Y))) ((? Z))) '((A (? X)) (B (? Y)) (C (? W)) (D (? Z))))

(princ "=======================")
(terpri)
(princ "Test 3: unify")
(terpri)
(princ "=======================")
(terpri)
(terpri)
(unify_test '(P (? x) B (? c)) '(P A (? y) (f A)) )